version: '3.8'

services:
  account-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - h2-data:/app/data
    restart: unless-stopped

volumes:
  h2-data: